FROM openjdk:11-slim as build



MAINTAINER eazybytes.com



COPY target/transactions-0.0.1-SNAPSHOT.jar transactions-0.0.1-SNAPSHOT.jar




ENTRYPOINT ["java","-jar","/transactions-0.0.1-SNAPSHOT.jar"]
